name: "CI - Lint, Test & Build"
run-name: CI - Run Lint, Test & Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: "Lint, test & build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v7

      - name: "Setup Node and install deps"
        uses: alderichoarau/gha-setup-node@v2

      - name: "Lint code"
        run: npm run lint

      - name: "Format check"
        run: npm run format:check

      - name: "Run tests"
        run: npm run test

      - name: "Build Angular app"
        run: npm run build:prod
